Add create and get all customers
ValentasK/The_Super_App pull request #4
Opened 2023-01-10 22:58 UTC by ValentasK

2023-01-10 23:22 UTC, KestasMil requested changes

2023-01-10 23:22 UTC, KestasMil commented on API.V1/Handlers/GetCustomerByIdHandler.cs
> +            string sql = "select * from [DapperDB].[dbo].[Person] as P\r\n  left join [DapperDB].[dbo].[Phone] as ph on p.CellPhoneId = ph.Id\t\r\n  where p.Id = @Id;";
Kam cia tie \r\n sql reikalingi?

2023-01-10 23:22 UTC, KestasMil commented on ConsoleApp_For_Katas/Program.cs
> +            var g = aaa.ToLower();
Kas cia per variable name 'aaa' ???

2023-01-10 23:22 UTC, KestasMil commented on The_Super_App/Program.cs
> +var cs = @"Server=(localdb)\MSSQLLocalDB;Database=DapperDB;Trusted_Connection=True;";
Connection string -> config file!

2023-01-10 23:22 UTC, KestasMil commented on API.V1/Handlers/GetAllOrdersHandller.cs
> +            string sql = "select * from [DapperDB].[dbo].[Person] as P\r\n  left join [DapperDB].[dbo].[Phone] as ph on p.CellPhoneId = ph.Id\t";
\r\n ???

2023-01-10 23:36 UTC, ValentasK commented on ConsoleApp_For_Katas/Program.cs
> +            var g = aaa.ToLower();
ConsoleApp_For_Katas vapsie cia net neturejo buti. Istrintas

2023-01-10 23:36 UTC, ValentasK commented on API.V1/Handlers/GetAllOrdersHandller.cs
> +            string sql = "select * from [DapperDB].[dbo].[Person] as P\r\n  left join [DapperDB].[dbo].[Phone] as ph on p.CellPhoneId = ph.Id\t";
Fixed.

2023-01-10 23:36 UTC, ValentasK commented on API.V1/Handlers/GetCustomerByIdHandler.cs
> +            string sql = "select * from [DapperDB].[dbo].[Person] as P\r\n  left join [DapperDB].[dbo].[Phone] as ph on p.CellPhoneId = ph.Id\t\r\n  where p.Id = @Id;";
Fixed

2023-01-10 23:37 UTC, ValentasK commented on The_Super_App/Program.cs
> +var cs = @"Server=(localdb)\MSSQLLocalDB;Database=DapperDB;Trusted_Connection=True;";
Ble sita reiks rytoj sutvarkyti

2023-01-11 20:15 UTC, ValentasK commented on The_Super_App/Program.cs
> +var cs = @"Server=(localdb)\MSSQLLocalDB;Database=DapperDB;Trusted_Connection=True;";
Fixed

2023-01-11 21:02 UTC, KestasMil requested changes

2023-01-11 21:02 UTC, KestasMil commented on API.V1/Program.cs
> +            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
Yes

2023-01-11 21:09 UTC, ValentasK commented on API.V1/Program.cs
> +            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
Not sure what is the question

2023-01-11 21:47 UTC, ValentasK commented on API.V1/Handlers/GetAllOrdersHandller.cs
> +            string? connectionString = _configuration.GetConnectionString("myDb1");
Done

2023-01-11 22:10 UTC, KestasMil approved these changes

2023-01-11 22:32 UTC, merged